apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonos-service
  labels:
    app: bonos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonos-service
  template:
    metadata:
      labels:
        app: bonos-service
    spec:
      containers:
        - name: bonos
          image: 403943113547.dkr.ecr.us-east-1.amazonaws.com/casino-bonos:latest
          ports:
            - containerPort: 8004
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "150m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8004
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8004
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bonos-service
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: bonos-service